name: build
on: [ pull_request, push ]

jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        java: [ 16 ]
        # and run on both Linux and Windows
        os: [ ubuntu-20.04 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Get commit id
        id: getid
        run: |
          echo "::set-output name=commitID::${GITHUB_SHA::7}"
      - name: Display commit id
        run: |
          echo MasaGadget commit-${{ steps.getid.outputs.commitID }} \(Public Beta\)
      - name: Set commit id in codes
        run: |
          sed -i "s/build.undefined/${{ steps.getid.outputs.commitID }}/g" gradle.properties
          sed -i "s/build.undefined/${{ steps.getid.outputs.commitID }}/g" src/main/java/com/plusls/MasaGadget/ModInfo.java
          sed -i "s/Version Exception/Public Beta/g" src/main/java/com/plusls/MasaGadget/ModInfo.java
      - name: Read relevant fields from gradle.properties
        id: properties
        run: |
          path='./gradle.properties'
          for property in minecraft_version_out mod_version_detail archives_base_name
          do
            result=$(sed -n "/^[[:space:]]*$property[[:space:]]*=[[:space:]]*/s/^[[:space:]]*$property[[:space:]]*=[[:space:]]*//p" "$path")
            echo "$property: $result"
            echo ::set-output name=$property::"$result"
          done
      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: capture build artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '16' }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.properties.outputs.archives_base_name }}-mc${{ steps.properties.outputs.minecraft_version_out }}-${{ steps.properties.outputs.mod_version_detail }}(Public Beta)
          path: build/libs/